######################################################################
# Automatically generated by qmake (3.0) mi� oct 14 00:17:36 2015
######################################################################

TEMPLATE = app
TARGET = gstvideo
INCLUDEPATH += .

# Input
HEADERS += gstvideo.h ui_gstvideo.h
FORMS += gstvideo.ui
SOURCES += gstvideo.cpp main.cpp
