#############################################################################
# Makefile for building: gstvideo
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  gstvideo.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile gstvideo.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -pthread -pthread -pthread -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -pthread -pthread -pthread -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -I. -Iscripts -I/usr/local/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -L/usr/local/lib -lgstvideo-1.0 -lgstaudio-1.0 -lgstbase-1.0 -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0 -lQt5Widgets -L/usr/lib/x86_64-linux-gnu -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = gstvideo.cpp \
		main.cpp \
		inputbox.cpp moc_gstvideo.cpp \
		moc_inputbox.cpp
OBJECTS       = gstvideo.o \
		main.o \
		inputbox.o \
		moc_gstvideo.o \
		moc_inputbox.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		gstvideo.pro \
		gstvideo.pro
QMAKE_TARGET  = gstvideo
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = gstvideo


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_gstvideo.h ui_inputbox.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: gstvideo.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		gstvideo.pro \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile gstvideo.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
gstvideo.pro:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile gstvideo.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/gstvideo1.0.0 || mkdir -p .tmp/gstvideo1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/gstvideo1.0.0/ && $(COPY_FILE) --parents gstvideo.h ui_gstvideo.h inputbox.h .tmp/gstvideo1.0.0/ && $(COPY_FILE) --parents gstvideo.cpp main.cpp inputbox.cpp .tmp/gstvideo1.0.0/ && $(COPY_FILE) --parents gstvideo.ui inputbox.ui .tmp/gstvideo1.0.0/ && (cd `dirname .tmp/gstvideo1.0.0` && $(TAR) gstvideo1.0.0.tar gstvideo1.0.0 && $(COMPRESS) gstvideo1.0.0.tar) && $(MOVE) `dirname .tmp/gstvideo1.0.0`/gstvideo1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/gstvideo1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_gstvideo.cpp moc_inputbox.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_gstvideo.cpp moc_inputbox.cpp
moc_gstvideo.cpp: /usr/include/qt5/QtWidgets/QWidget \
		/usr/include/qt5/QtWidgets/qwidget.h \
		/usr/include/qt5/QtGui/qwindowdefs.h \
		/usr/include/qt5/QtCore/qglobal.h \
		/usr/include/qt5/QtCore/qconfig.h \
		/usr/include/qt5/QtCore/qfeatures.h \
		/usr/include/qt5/QtCore/qsystemdetection.h \
		/usr/include/qt5/QtCore/qprocessordetection.h \
		/usr/include/qt5/QtCore/qcompilerdetection.h \
		/usr/include/qt5/QtCore/qglobalstatic.h \
		/usr/include/qt5/QtCore/qatomic.h \
		/usr/include/qt5/QtCore/qbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/qt5/QtCore/qgenericatomic.h \
		/usr/include/qt5/QtCore/qatomic_msvc.h \
		/usr/include/qt5/QtCore/qatomic_integrity.h \
		/usr/include/qt5/QtCore/qoldbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_vxworks.h \
		/usr/include/qt5/QtCore/qatomic_power.h \
		/usr/include/qt5/QtCore/qatomic_alpha.h \
		/usr/include/qt5/QtCore/qatomic_armv7.h \
		/usr/include/qt5/QtCore/qatomic_armv6.h \
		/usr/include/qt5/QtCore/qatomic_armv5.h \
		/usr/include/qt5/QtCore/qatomic_bfin.h \
		/usr/include/qt5/QtCore/qatomic_ia64.h \
		/usr/include/qt5/QtCore/qatomic_mips.h \
		/usr/include/qt5/QtCore/qatomic_s390.h \
		/usr/include/qt5/QtCore/qatomic_sh4a.h \
		/usr/include/qt5/QtCore/qatomic_sparc.h \
		/usr/include/qt5/QtCore/qatomic_gcc.h \
		/usr/include/qt5/QtCore/qatomic_x86.h \
		/usr/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/qt5/QtCore/qatomic_unix.h \
		/usr/include/qt5/QtCore/qmutex.h \
		/usr/include/qt5/QtCore/qlogging.h \
		/usr/include/qt5/QtCore/qflags.h \
		/usr/include/qt5/QtCore/qtypeinfo.h \
		/usr/include/qt5/QtCore/qtypetraits.h \
		/usr/include/qt5/QtCore/qsysinfo.h \
		/usr/include/qt5/QtCore/qobjectdefs.h \
		/usr/include/qt5/QtCore/qnamespace.h \
		/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/qt5/QtCore/qobject.h \
		/usr/include/qt5/QtCore/qstring.h \
		/usr/include/qt5/QtCore/qchar.h \
		/usr/include/qt5/QtCore/qbytearray.h \
		/usr/include/qt5/QtCore/qrefcount.h \
		/usr/include/qt5/QtCore/qarraydata.h \
		/usr/include/qt5/QtCore/qstringbuilder.h \
		/usr/include/qt5/QtCore/qlist.h \
		/usr/include/qt5/QtCore/qalgorithms.h \
		/usr/include/qt5/QtCore/qiterator.h \
		/usr/include/qt5/QtCore/qcoreevent.h \
		/usr/include/qt5/QtCore/qscopedpointer.h \
		/usr/include/qt5/QtCore/qmetatype.h \
		/usr/include/qt5/QtCore/qvarlengtharray.h \
		/usr/include/qt5/QtCore/qcontainerfwd.h \
		/usr/include/qt5/QtCore/qisenum.h \
		/usr/include/qt5/QtCore/qobject_impl.h \
		/usr/include/qt5/QtCore/qmargins.h \
		/usr/include/qt5/QtCore/qrect.h \
		/usr/include/qt5/QtCore/qsize.h \
		/usr/include/qt5/QtCore/qpoint.h \
		/usr/include/qt5/QtGui/qpaintdevice.h \
		/usr/include/qt5/QtGui/qpalette.h \
		/usr/include/qt5/QtGui/qcolor.h \
		/usr/include/qt5/QtGui/qrgb.h \
		/usr/include/qt5/QtCore/qstringlist.h \
		/usr/include/qt5/QtCore/qdatastream.h \
		/usr/include/qt5/QtCore/qiodevice.h \
		/usr/include/qt5/QtCore/qpair.h \
		/usr/include/qt5/QtCore/qregexp.h \
		/usr/include/qt5/QtCore/qstringmatcher.h \
		/usr/include/qt5/QtGui/qbrush.h \
		/usr/include/qt5/QtCore/qvector.h \
		/usr/include/qt5/QtGui/qmatrix.h \
		/usr/include/qt5/QtGui/qpolygon.h \
		/usr/include/qt5/QtGui/qregion.h \
		/usr/include/qt5/QtCore/qline.h \
		/usr/include/qt5/QtGui/qtransform.h \
		/usr/include/qt5/QtGui/qpainterpath.h \
		/usr/include/qt5/QtGui/qimage.h \
		/usr/include/qt5/QtGui/qpixmap.h \
		/usr/include/qt5/QtCore/qsharedpointer.h \
		/usr/include/qt5/QtCore/qshareddata.h \
		/usr/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/qt5/QtCore/qhash.h \
		/usr/include/qt5/QtGui/qfont.h \
		/usr/include/qt5/QtGui/qfontmetrics.h \
		/usr/include/qt5/QtGui/qfontinfo.h \
		/usr/include/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/qt5/QtGui/qcursor.h \
		/usr/include/qt5/QtGui/qkeysequence.h \
		/usr/include/qt5/QtGui/qevent.h \
		/usr/include/qt5/QtCore/qvariant.h \
		/usr/include/qt5/QtCore/qmap.h \
		/usr/include/qt5/QtCore/qdebug.h \
		/usr/include/qt5/QtCore/qtextstream.h \
		/usr/include/qt5/QtCore/qlocale.h \
		/usr/include/qt5/QtCore/qset.h \
		/usr/include/qt5/QtCore/qcontiguouscache.h \
		/usr/include/qt5/QtCore/qurl.h \
		/usr/include/qt5/QtCore/qurlquery.h \
		/usr/include/qt5/QtCore/qfile.h \
		/usr/include/qt5/QtCore/qfiledevice.h \
		/usr/include/qt5/QtGui/qvector2d.h \
		/usr/include/qt5/QtGui/qtouchdevice.h \
		/usr/include/glib-2.0/glib.h \
		/usr/include/glib-2.0/glib/galloca.h \
		/usr/include/glib-2.0/glib/gtypes.h \
		/usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h \
		/usr/include/glib-2.0/glib/gmacros.h \
		/usr/include/glib-2.0/glib/gversionmacros.h \
		/usr/include/glib-2.0/glib/garray.h \
		/usr/include/glib-2.0/glib/gasyncqueue.h \
		/usr/include/glib-2.0/glib/gthread.h \
		/usr/include/glib-2.0/glib/gatomic.h \
		/usr/include/glib-2.0/glib/gerror.h \
		/usr/include/glib-2.0/glib/gquark.h \
		/usr/include/glib-2.0/glib/gbacktrace.h \
		/usr/include/glib-2.0/glib/gbase64.h \
		/usr/include/glib-2.0/glib/gbitlock.h \
		/usr/include/glib-2.0/glib/gbookmarkfile.h \
		/usr/include/glib-2.0/glib/gbytes.h \
		/usr/include/glib-2.0/glib/gcharset.h \
		/usr/include/glib-2.0/glib/gchecksum.h \
		/usr/include/glib-2.0/glib/gconvert.h \
		/usr/include/glib-2.0/glib/gdataset.h \
		/usr/include/glib-2.0/glib/gdate.h \
		/usr/include/glib-2.0/glib/gdatetime.h \
		/usr/include/glib-2.0/glib/gtimezone.h \
		/usr/include/glib-2.0/glib/gdir.h \
		/usr/include/glib-2.0/glib/genviron.h \
		/usr/include/glib-2.0/glib/gfileutils.h \
		/usr/include/glib-2.0/glib/ggettext.h \
		/usr/include/glib-2.0/glib/ghash.h \
		/usr/include/glib-2.0/glib/glist.h \
		/usr/include/glib-2.0/glib/gmem.h \
		/usr/include/glib-2.0/glib/gnode.h \
		/usr/include/glib-2.0/glib/ghmac.h \
		/usr/include/glib-2.0/glib/ghook.h \
		/usr/include/glib-2.0/glib/ghostutils.h \
		/usr/include/glib-2.0/glib/giochannel.h \
		/usr/include/glib-2.0/glib/gmain.h \
		/usr/include/glib-2.0/glib/gpoll.h \
		/usr/include/glib-2.0/glib/gslist.h \
		/usr/include/glib-2.0/glib/gstring.h \
		/usr/include/glib-2.0/glib/gunicode.h \
		/usr/include/glib-2.0/glib/gutils.h \
		/usr/include/glib-2.0/glib/gkeyfile.h \
		/usr/include/glib-2.0/glib/gmappedfile.h \
		/usr/include/glib-2.0/glib/gmarkup.h \
		/usr/include/glib-2.0/glib/gmessages.h \
		/usr/include/glib-2.0/glib/goption.h \
		/usr/include/glib-2.0/glib/gpattern.h \
		/usr/include/glib-2.0/glib/gprimes.h \
		/usr/include/glib-2.0/glib/gqsort.h \
		/usr/include/glib-2.0/glib/gqueue.h \
		/usr/include/glib-2.0/glib/grand.h \
		/usr/include/glib-2.0/glib/gregex.h \
		/usr/include/glib-2.0/glib/gscanner.h \
		/usr/include/glib-2.0/glib/gsequence.h \
		/usr/include/glib-2.0/glib/gshell.h \
		/usr/include/glib-2.0/glib/gslice.h \
		/usr/include/glib-2.0/glib/gspawn.h \
		/usr/include/glib-2.0/glib/gstrfuncs.h \
		/usr/include/glib-2.0/glib/gstringchunk.h \
		/usr/include/glib-2.0/glib/gtestutils.h \
		/usr/include/glib-2.0/glib/gthreadpool.h \
		/usr/include/glib-2.0/glib/gtimer.h \
		/usr/include/glib-2.0/glib/gtrashstack.h \
		/usr/include/glib-2.0/glib/gtree.h \
		/usr/include/glib-2.0/glib/gurifuncs.h \
		/usr/include/glib-2.0/glib/gvarianttype.h \
		/usr/include/glib-2.0/glib/gvariant.h \
		/usr/include/glib-2.0/glib/gversion.h \
		/usr/include/glib-2.0/glib/gwin32.h \
		/usr/include/glib-2.0/glib/deprecated/gallocator.h \
		/usr/include/glib-2.0/glib/deprecated/gcache.h \
		/usr/include/glib-2.0/glib/deprecated/gcompletion.h \
		/usr/include/glib-2.0/glib/deprecated/gmain.h \
		/usr/include/glib-2.0/glib/deprecated/grel.h \
		/usr/include/glib-2.0/glib/deprecated/gthread.h \
		/usr/local/include/gstreamer-1.0/gst/gst.h \
		/usr/local/include/gstreamer-1.0/gst/glib-compat.h \
		/usr/local/include/gstreamer-1.0/gst/gstenumtypes.h \
		/usr/include/glib-2.0/glib-object.h \
		/usr/include/glib-2.0/gobject/gbinding.h \
		/usr/include/glib-2.0/gobject/gobject.h \
		/usr/include/glib-2.0/gobject/gtype.h \
		/usr/include/glib-2.0/gobject/gvalue.h \
		/usr/include/glib-2.0/gobject/gparam.h \
		/usr/include/glib-2.0/gobject/gclosure.h \
		/usr/include/glib-2.0/gobject/gsignal.h \
		/usr/include/glib-2.0/gobject/gmarshal.h \
		/usr/include/glib-2.0/gobject/gboxed.h \
		/usr/include/glib-2.0/gobject/glib-types.h \
		/usr/include/glib-2.0/gobject/genums.h \
		/usr/include/glib-2.0/gobject/gparamspecs.h \
		/usr/include/glib-2.0/gobject/gsourceclosure.h \
		/usr/include/glib-2.0/gobject/gtypemodule.h \
		/usr/include/glib-2.0/gobject/gtypeplugin.h \
		/usr/include/glib-2.0/gobject/gvaluearray.h \
		/usr/include/glib-2.0/gobject/gvaluetypes.h \
		/usr/local/include/gstreamer-1.0/gst/gstversion.h \
		/usr/local/include/gstreamer-1.0/gst/gstatomicqueue.h \
		/usr/local/include/gstreamer-1.0/gst/gstbin.h \
		/usr/local/include/gstreamer-1.0/gst/gstelement.h \
		/usr/local/include/gstreamer-1.0/gst/gstconfig.h \
		/usr/local/include/gstreamer-1.0/gst/gstobject.h \
		/usr/local/include/gstreamer-1.0/gst/gstcontrolbinding.h \
		/usr/local/include/gstreamer-1.0/gst/gstcontrolsource.h \
		/usr/local/include/gstreamer-1.0/gst/gstclock.h \
		/usr/local/include/gstreamer-1.0/gst/gstpad.h \
		/usr/local/include/gstreamer-1.0/gst/gstbuffer.h \
		/usr/local/include/gstreamer-1.0/gst/gstminiobject.h \
		/usr/local/include/gstreamer-1.0/gst/gstallocator.h \
		/usr/local/include/gstreamer-1.0/gst/gstmemory.h \
		/usr/local/include/gstreamer-1.0/gst/gstmeta.h \
		/usr/local/include/gstreamer-1.0/gst/gstbufferlist.h \
		/usr/local/include/gstreamer-1.0/gst/gstcaps.h \
		/usr/local/include/gstreamer-1.0/gst/gststructure.h \
		/usr/local/include/gstreamer-1.0/gst/gstdatetime.h \
		/usr/local/include/gstreamer-1.0/gst/gstcapsfeatures.h \
		/usr/local/include/gstreamer-1.0/gst/gstpadtemplate.h \
		/usr/local/include/gstreamer-1.0/gst/gstevent.h \
		/usr/local/include/gstreamer-1.0/gst/gstformat.h \
		/usr/local/include/gstreamer-1.0/gst/gstiterator.h \
		/usr/local/include/gstreamer-1.0/gst/gsttaglist.h \
		/usr/local/include/gstreamer-1.0/gst/gstsample.h \
		/usr/local/include/gstreamer-1.0/gst/gstsegment.h \
		/usr/local/include/gstreamer-1.0/gst/gstmessage.h \
		/usr/local/include/gstreamer-1.0/gst/gstquery.h \
		/usr/local/include/gstreamer-1.0/gst/gsttoc.h \
		/usr/local/include/gstreamer-1.0/gst/gstcontext.h \
		/usr/local/include/gstreamer-1.0/gst/gstdevice.h \
		/usr/local/include/gstreamer-1.0/gst/gsttask.h \
		/usr/local/include/gstreamer-1.0/gst/gsttaskpool.h \
		/usr/local/include/gstreamer-1.0/gst/gstbus.h \
		/usr/local/include/gstreamer-1.0/gst/gstelementfactory.h \
		/usr/local/include/gstreamer-1.0/gst/gstplugin.h \
		/usr/local/include/gstreamer-1.0/gst/gstmacros.h \
		/usr/local/include/gstreamer-1.0/gst/gstpluginfeature.h \
		/usr/local/include/gstreamer-1.0/gst/gsturi.h \
		/usr/local/include/gstreamer-1.0/gst/gstbufferpool.h \
		/usr/local/include/gstreamer-1.0/gst/gstchildproxy.h \
		/usr/local/include/gstreamer-1.0/gst/gstdebugutils.h \
		/usr/local/include/gstreamer-1.0/gst/gstdeviceprovider.h \
		/usr/local/include/gstreamer-1.0/gst/gstdeviceproviderfactory.h \
		/usr/local/include/gstreamer-1.0/gst/gstelementmetadata.h \
		/usr/local/include/gstreamer-1.0/gst/gsterror.h \
		/usr/local/include/gstreamer-1.0/gst/gstghostpad.h \
		/usr/local/include/gstreamer-1.0/gst/gstdevicemonitor.h \
		/usr/local/include/gstreamer-1.0/gst/gstinfo.h \
		/usr/local/include/gstreamer-1.0/gst/gstparamspecs.h \
		/usr/local/include/gstreamer-1.0/gst/gstvalue.h \
		/usr/local/include/gstreamer-1.0/gst/gstpipeline.h \
		/usr/local/include/gstreamer-1.0/gst/gstpoll.h \
		/usr/local/include/gstreamer-1.0/gst/gstpreset.h \
		/usr/local/include/gstreamer-1.0/gst/gstregistry.h \
		/usr/local/include/gstreamer-1.0/gst/gstsystemclock.h \
		/usr/local/include/gstreamer-1.0/gst/gsttagsetter.h \
		/usr/local/include/gstreamer-1.0/gst/gsttocsetter.h \
		/usr/local/include/gstreamer-1.0/gst/gsttypefind.h \
		/usr/local/include/gstreamer-1.0/gst/gsttypefindfactory.h \
		/usr/local/include/gstreamer-1.0/gst/gstutils.h \
		/usr/local/include/gstreamer-1.0/gst/gstparse.h \
		/usr/local/include/gstreamer-1.0/gst/gstcompat.h \
		/usr/local/include/gstreamer-1.0/gst/video/colorbalance.h \
		/usr/local/include/gstreamer-1.0/gst/video/colorbalancechannel.h \
		/usr/local/include/gstreamer-1.0/gst/video/videooverlay.h \
		/usr/include/qt5/QtWidgets/QMessageBox \
		/usr/include/qt5/QtWidgets/qmessagebox.h \
		/usr/include/qt5/QtWidgets/qdialog.h \
		/usr/include/qt5/QtWidgets/QSlider \
		/usr/include/qt5/QtWidgets/qslider.h \
		/usr/include/qt5/QtWidgets/qabstractslider.h \
		/usr/include/qt5/QtWidgets/QLineEdit \
		/usr/include/qt5/QtWidgets/qlineedit.h \
		/usr/include/qt5/QtWidgets/qframe.h \
		/usr/include/qt5/QtGui/qtextcursor.h \
		/usr/include/qt5/QtGui/qtextformat.h \
		/usr/include/qt5/QtGui/qpen.h \
		/usr/include/qt5/QtGui/qtextoption.h \
		/usr/local/include/gstreamer-1.0/gst/audio/streamvolume.h \
		ui_gstvideo.h \
		/usr/include/qt5/QtCore/QVariant \
		/usr/include/qt5/QtWidgets/QAction \
		/usr/include/qt5/QtWidgets/qaction.h \
		/usr/include/qt5/QtGui/qicon.h \
		/usr/include/qt5/QtWidgets/qactiongroup.h \
		/usr/include/qt5/QtWidgets/QApplication \
		/usr/include/qt5/QtWidgets/qapplication.h \
		/usr/include/qt5/QtCore/qcoreapplication.h \
		/usr/include/qt5/QtCore/qeventloop.h \
		/usr/include/qt5/QtWidgets/qdesktopwidget.h \
		/usr/include/qt5/QtGui/qguiapplication.h \
		/usr/include/qt5/QtGui/qinputmethod.h \
		/usr/include/qt5/QtWidgets/QButtonGroup \
		/usr/include/qt5/QtWidgets/qbuttongroup.h \
		/usr/include/qt5/QtWidgets/QComboBox \
		/usr/include/qt5/QtWidgets/qcombobox.h \
		/usr/include/qt5/QtWidgets/qabstractitemdelegate.h \
		/usr/include/qt5/QtWidgets/qstyleoption.h \
		/usr/include/qt5/QtWidgets/qabstractspinbox.h \
		/usr/include/qt5/QtGui/qvalidator.h \
		/usr/include/qt5/QtCore/qregularexpression.h \
		/usr/include/qt5/QtWidgets/qstyle.h \
		/usr/include/qt5/QtWidgets/qtabbar.h \
		/usr/include/qt5/QtWidgets/qtabwidget.h \
		/usr/include/qt5/QtWidgets/qrubberband.h \
		/usr/include/qt5/QtCore/qabstractitemmodel.h \
		/usr/include/qt5/QtWidgets/QHBoxLayout \
		/usr/include/qt5/QtWidgets/qboxlayout.h \
		/usr/include/qt5/QtWidgets/qlayout.h \
		/usr/include/qt5/QtWidgets/qlayoutitem.h \
		/usr/include/qt5/QtWidgets/qgridlayout.h \
		/usr/include/qt5/QtWidgets/QHeaderView \
		/usr/include/qt5/QtWidgets/qheaderview.h \
		/usr/include/qt5/QtWidgets/qabstractitemview.h \
		/usr/include/qt5/QtWidgets/qabstractscrollarea.h \
		/usr/include/qt5/QtCore/qitemselectionmodel.h \
		/usr/include/qt5/QtWidgets/QLabel \
		/usr/include/qt5/QtWidgets/qlabel.h \
		/usr/include/qt5/QtWidgets/QProgressBar \
		/usr/include/qt5/QtWidgets/qprogressbar.h \
		/usr/include/qt5/QtWidgets/QToolButton \
		/usr/include/qt5/QtWidgets/qtoolbutton.h \
		/usr/include/qt5/QtWidgets/qabstractbutton.h \
		/usr/include/qt5/QtWidgets/QVBoxLayout \
		inputbox.h \
		/usr/include/qt5/QtWidgets/QDialog \
		/usr/include/qt5/QtCore/QString \
		gstvideo.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) $(INCPATH) -I/usr/include/c++/4.8 -I/usr/include/x86_64-linux-gnu/c++/4.8 -I/usr/include/c++/4.8/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include gstvideo.h -o moc_gstvideo.cpp

moc_inputbox.cpp: /usr/include/qt5/QtWidgets/QDialog \
		/usr/include/qt5/QtWidgets/qdialog.h \
		/usr/include/qt5/QtWidgets/qwidget.h \
		/usr/include/qt5/QtGui/qwindowdefs.h \
		/usr/include/qt5/QtCore/qglobal.h \
		/usr/include/qt5/QtCore/qconfig.h \
		/usr/include/qt5/QtCore/qfeatures.h \
		/usr/include/qt5/QtCore/qsystemdetection.h \
		/usr/include/qt5/QtCore/qprocessordetection.h \
		/usr/include/qt5/QtCore/qcompilerdetection.h \
		/usr/include/qt5/QtCore/qglobalstatic.h \
		/usr/include/qt5/QtCore/qatomic.h \
		/usr/include/qt5/QtCore/qbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/qt5/QtCore/qgenericatomic.h \
		/usr/include/qt5/QtCore/qatomic_msvc.h \
		/usr/include/qt5/QtCore/qatomic_integrity.h \
		/usr/include/qt5/QtCore/qoldbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_vxworks.h \
		/usr/include/qt5/QtCore/qatomic_power.h \
		/usr/include/qt5/QtCore/qatomic_alpha.h \
		/usr/include/qt5/QtCore/qatomic_armv7.h \
		/usr/include/qt5/QtCore/qatomic_armv6.h \
		/usr/include/qt5/QtCore/qatomic_armv5.h \
		/usr/include/qt5/QtCore/qatomic_bfin.h \
		/usr/include/qt5/QtCore/qatomic_ia64.h \
		/usr/include/qt5/QtCore/qatomic_mips.h \
		/usr/include/qt5/QtCore/qatomic_s390.h \
		/usr/include/qt5/QtCore/qatomic_sh4a.h \
		/usr/include/qt5/QtCore/qatomic_sparc.h \
		/usr/include/qt5/QtCore/qatomic_gcc.h \
		/usr/include/qt5/QtCore/qatomic_x86.h \
		/usr/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/qt5/QtCore/qatomic_unix.h \
		/usr/include/qt5/QtCore/qmutex.h \
		/usr/include/qt5/QtCore/qlogging.h \
		/usr/include/qt5/QtCore/qflags.h \
		/usr/include/qt5/QtCore/qtypeinfo.h \
		/usr/include/qt5/QtCore/qtypetraits.h \
		/usr/include/qt5/QtCore/qsysinfo.h \
		/usr/include/qt5/QtCore/qobjectdefs.h \
		/usr/include/qt5/QtCore/qnamespace.h \
		/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/qt5/QtCore/qobject.h \
		/usr/include/qt5/QtCore/qstring.h \
		/usr/include/qt5/QtCore/qchar.h \
		/usr/include/qt5/QtCore/qbytearray.h \
		/usr/include/qt5/QtCore/qrefcount.h \
		/usr/include/qt5/QtCore/qarraydata.h \
		/usr/include/qt5/QtCore/qstringbuilder.h \
		/usr/include/qt5/QtCore/qlist.h \
		/usr/include/qt5/QtCore/qalgorithms.h \
		/usr/include/qt5/QtCore/qiterator.h \
		/usr/include/qt5/QtCore/qcoreevent.h \
		/usr/include/qt5/QtCore/qscopedpointer.h \
		/usr/include/qt5/QtCore/qmetatype.h \
		/usr/include/qt5/QtCore/qvarlengtharray.h \
		/usr/include/qt5/QtCore/qcontainerfwd.h \
		/usr/include/qt5/QtCore/qisenum.h \
		/usr/include/qt5/QtCore/qobject_impl.h \
		/usr/include/qt5/QtCore/qmargins.h \
		/usr/include/qt5/QtCore/qrect.h \
		/usr/include/qt5/QtCore/qsize.h \
		/usr/include/qt5/QtCore/qpoint.h \
		/usr/include/qt5/QtGui/qpaintdevice.h \
		/usr/include/qt5/QtGui/qpalette.h \
		/usr/include/qt5/QtGui/qcolor.h \
		/usr/include/qt5/QtGui/qrgb.h \
		/usr/include/qt5/QtCore/qstringlist.h \
		/usr/include/qt5/QtCore/qdatastream.h \
		/usr/include/qt5/QtCore/qiodevice.h \
		/usr/include/qt5/QtCore/qpair.h \
		/usr/include/qt5/QtCore/qregexp.h \
		/usr/include/qt5/QtCore/qstringmatcher.h \
		/usr/include/qt5/QtGui/qbrush.h \
		/usr/include/qt5/QtCore/qvector.h \
		/usr/include/qt5/QtGui/qmatrix.h \
		/usr/include/qt5/QtGui/qpolygon.h \
		/usr/include/qt5/QtGui/qregion.h \
		/usr/include/qt5/QtCore/qline.h \
		/usr/include/qt5/QtGui/qtransform.h \
		/usr/include/qt5/QtGui/qpainterpath.h \
		/usr/include/qt5/QtGui/qimage.h \
		/usr/include/qt5/QtGui/qpixmap.h \
		/usr/include/qt5/QtCore/qsharedpointer.h \
		/usr/include/qt5/QtCore/qshareddata.h \
		/usr/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/qt5/QtCore/qhash.h \
		/usr/include/qt5/QtGui/qfont.h \
		/usr/include/qt5/QtGui/qfontmetrics.h \
		/usr/include/qt5/QtGui/qfontinfo.h \
		/usr/include/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/qt5/QtGui/qcursor.h \
		/usr/include/qt5/QtGui/qkeysequence.h \
		/usr/include/qt5/QtGui/qevent.h \
		/usr/include/qt5/QtCore/qvariant.h \
		/usr/include/qt5/QtCore/qmap.h \
		/usr/include/qt5/QtCore/qdebug.h \
		/usr/include/qt5/QtCore/qtextstream.h \
		/usr/include/qt5/QtCore/qlocale.h \
		/usr/include/qt5/QtCore/qset.h \
		/usr/include/qt5/QtCore/qcontiguouscache.h \
		/usr/include/qt5/QtCore/qurl.h \
		/usr/include/qt5/QtCore/qurlquery.h \
		/usr/include/qt5/QtCore/qfile.h \
		/usr/include/qt5/QtCore/qfiledevice.h \
		/usr/include/qt5/QtGui/qvector2d.h \
		/usr/include/qt5/QtGui/qtouchdevice.h \
		/usr/include/qt5/QtCore/QString \
		inputbox.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) $(INCPATH) -I/usr/include/c++/4.8 -I/usr/include/x86_64-linux-gnu/c++/4.8 -I/usr/include/c++/4.8/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include inputbox.h -o moc_inputbox.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_gstvideo.h ui_inputbox.h
compiler_uic_clean:
	-$(DEL_FILE) ui_gstvideo.h ui_inputbox.h
ui_gstvideo.h: gstvideo.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic gstvideo.ui -o ui_gstvideo.h

ui_inputbox.h: inputbox.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic inputbox.ui -o ui_inputbox.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

gstvideo.o: gstvideo.cpp gstvideo.h \
		/usr/include/qt5/QtWidgets/QWidget \
		/usr/include/qt5/QtWidgets/qwidget.h \
		/usr/include/qt5/QtGui/qwindowdefs.h \
		/usr/include/qt5/QtCore/qglobal.h \
		/usr/include/qt5/QtCore/qconfig.h \
		/usr/include/qt5/QtCore/qfeatures.h \
		/usr/include/qt5/QtCore/qsystemdetection.h \
		/usr/include/qt5/QtCore/qprocessordetection.h \
		/usr/include/qt5/QtCore/qcompilerdetection.h \
		/usr/include/qt5/QtCore/qglobalstatic.h \
		/usr/include/qt5/QtCore/qatomic.h \
		/usr/include/qt5/QtCore/qbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/qt5/QtCore/qgenericatomic.h \
		/usr/include/qt5/QtCore/qatomic_msvc.h \
		/usr/include/qt5/QtCore/qatomic_integrity.h \
		/usr/include/qt5/QtCore/qoldbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_vxworks.h \
		/usr/include/qt5/QtCore/qatomic_power.h \
		/usr/include/qt5/QtCore/qatomic_alpha.h \
		/usr/include/qt5/QtCore/qatomic_armv7.h \
		/usr/include/qt5/QtCore/qatomic_armv6.h \
		/usr/include/qt5/QtCore/qatomic_armv5.h \
		/usr/include/qt5/QtCore/qatomic_bfin.h \
		/usr/include/qt5/QtCore/qatomic_ia64.h \
		/usr/include/qt5/QtCore/qatomic_mips.h \
		/usr/include/qt5/QtCore/qatomic_s390.h \
		/usr/include/qt5/QtCore/qatomic_sh4a.h \
		/usr/include/qt5/QtCore/qatomic_sparc.h \
		/usr/include/qt5/QtCore/qatomic_gcc.h \
		/usr/include/qt5/QtCore/qatomic_x86.h \
		/usr/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/qt5/QtCore/qatomic_unix.h \
		/usr/include/qt5/QtCore/qmutex.h \
		/usr/include/qt5/QtCore/qlogging.h \
		/usr/include/qt5/QtCore/qflags.h \
		/usr/include/qt5/QtCore/qtypeinfo.h \
		/usr/include/qt5/QtCore/qtypetraits.h \
		/usr/include/qt5/QtCore/qsysinfo.h \
		/usr/include/qt5/QtCore/qobjectdefs.h \
		/usr/include/qt5/QtCore/qnamespace.h \
		/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/qt5/QtCore/qobject.h \
		/usr/include/qt5/QtCore/qstring.h \
		/usr/include/qt5/QtCore/qchar.h \
		/usr/include/qt5/QtCore/qbytearray.h \
		/usr/include/qt5/QtCore/qrefcount.h \
		/usr/include/qt5/QtCore/qarraydata.h \
		/usr/include/qt5/QtCore/qstringbuilder.h \
		/usr/include/qt5/QtCore/qlist.h \
		/usr/include/qt5/QtCore/qalgorithms.h \
		/usr/include/qt5/QtCore/qiterator.h \
		/usr/include/qt5/QtCore/qcoreevent.h \
		/usr/include/qt5/QtCore/qscopedpointer.h \
		/usr/include/qt5/QtCore/qmetatype.h \
		/usr/include/qt5/QtCore/qvarlengtharray.h \
		/usr/include/qt5/QtCore/qcontainerfwd.h \
		/usr/include/qt5/QtCore/qisenum.h \
		/usr/include/qt5/QtCore/qobject_impl.h \
		/usr/include/qt5/QtCore/qmargins.h \
		/usr/include/qt5/QtCore/qrect.h \
		/usr/include/qt5/QtCore/qsize.h \
		/usr/include/qt5/QtCore/qpoint.h \
		/usr/include/qt5/QtGui/qpaintdevice.h \
		/usr/include/qt5/QtGui/qpalette.h \
		/usr/include/qt5/QtGui/qcolor.h \
		/usr/include/qt5/QtGui/qrgb.h \
		/usr/include/qt5/QtCore/qstringlist.h \
		/usr/include/qt5/QtCore/qdatastream.h \
		/usr/include/qt5/QtCore/qiodevice.h \
		/usr/include/qt5/QtCore/qpair.h \
		/usr/include/qt5/QtCore/qregexp.h \
		/usr/include/qt5/QtCore/qstringmatcher.h \
		/usr/include/qt5/QtGui/qbrush.h \
		/usr/include/qt5/QtCore/qvector.h \
		/usr/include/qt5/QtGui/qmatrix.h \
		/usr/include/qt5/QtGui/qpolygon.h \
		/usr/include/qt5/QtGui/qregion.h \
		/usr/include/qt5/QtCore/qline.h \
		/usr/include/qt5/QtGui/qtransform.h \
		/usr/include/qt5/QtGui/qpainterpath.h \
		/usr/include/qt5/QtGui/qimage.h \
		/usr/include/qt5/QtGui/qpixmap.h \
		/usr/include/qt5/QtCore/qsharedpointer.h \
		/usr/include/qt5/QtCore/qshareddata.h \
		/usr/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/qt5/QtCore/qhash.h \
		/usr/include/qt5/QtGui/qfont.h \
		/usr/include/qt5/QtGui/qfontmetrics.h \
		/usr/include/qt5/QtGui/qfontinfo.h \
		/usr/include/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/qt5/QtGui/qcursor.h \
		/usr/include/qt5/QtGui/qkeysequence.h \
		/usr/include/qt5/QtGui/qevent.h \
		/usr/include/qt5/QtCore/qvariant.h \
		/usr/include/qt5/QtCore/qmap.h \
		/usr/include/qt5/QtCore/qdebug.h \
		/usr/include/qt5/QtCore/qtextstream.h \
		/usr/include/qt5/QtCore/qlocale.h \
		/usr/include/qt5/QtCore/qset.h \
		/usr/include/qt5/QtCore/qcontiguouscache.h \
		/usr/include/qt5/QtCore/qurl.h \
		/usr/include/qt5/QtCore/qurlquery.h \
		/usr/include/qt5/QtCore/qfile.h \
		/usr/include/qt5/QtCore/qfiledevice.h \
		/usr/include/qt5/QtGui/qvector2d.h \
		/usr/include/qt5/QtGui/qtouchdevice.h \
		/usr/include/glib-2.0/glib.h \
		/usr/include/glib-2.0/glib/galloca.h \
		/usr/include/glib-2.0/glib/gtypes.h \
		/usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h \
		/usr/include/glib-2.0/glib/gmacros.h \
		/usr/include/glib-2.0/glib/gversionmacros.h \
		/usr/include/glib-2.0/glib/garray.h \
		/usr/include/glib-2.0/glib/gasyncqueue.h \
		/usr/include/glib-2.0/glib/gthread.h \
		/usr/include/glib-2.0/glib/gatomic.h \
		/usr/include/glib-2.0/glib/gerror.h \
		/usr/include/glib-2.0/glib/gquark.h \
		/usr/include/glib-2.0/glib/gbacktrace.h \
		/usr/include/glib-2.0/glib/gbase64.h \
		/usr/include/glib-2.0/glib/gbitlock.h \
		/usr/include/glib-2.0/glib/gbookmarkfile.h \
		/usr/include/glib-2.0/glib/gbytes.h \
		/usr/include/glib-2.0/glib/gcharset.h \
		/usr/include/glib-2.0/glib/gchecksum.h \
		/usr/include/glib-2.0/glib/gconvert.h \
		/usr/include/glib-2.0/glib/gdataset.h \
		/usr/include/glib-2.0/glib/gdate.h \
		/usr/include/glib-2.0/glib/gdatetime.h \
		/usr/include/glib-2.0/glib/gtimezone.h \
		/usr/include/glib-2.0/glib/gdir.h \
		/usr/include/glib-2.0/glib/genviron.h \
		/usr/include/glib-2.0/glib/gfileutils.h \
		/usr/include/glib-2.0/glib/ggettext.h \
		/usr/include/glib-2.0/glib/ghash.h \
		/usr/include/glib-2.0/glib/glist.h \
		/usr/include/glib-2.0/glib/gmem.h \
		/usr/include/glib-2.0/glib/gnode.h \
		/usr/include/glib-2.0/glib/ghmac.h \
		/usr/include/glib-2.0/glib/ghook.h \
		/usr/include/glib-2.0/glib/ghostutils.h \
		/usr/include/glib-2.0/glib/giochannel.h \
		/usr/include/glib-2.0/glib/gmain.h \
		/usr/include/glib-2.0/glib/gpoll.h \
		/usr/include/glib-2.0/glib/gslist.h \
		/usr/include/glib-2.0/glib/gstring.h \
		/usr/include/glib-2.0/glib/gunicode.h \
		/usr/include/glib-2.0/glib/gutils.h \
		/usr/include/glib-2.0/glib/gkeyfile.h \
		/usr/include/glib-2.0/glib/gmappedfile.h \
		/usr/include/glib-2.0/glib/gmarkup.h \
		/usr/include/glib-2.0/glib/gmessages.h \
		/usr/include/glib-2.0/glib/goption.h \
		/usr/include/glib-2.0/glib/gpattern.h \
		/usr/include/glib-2.0/glib/gprimes.h \
		/usr/include/glib-2.0/glib/gqsort.h \
		/usr/include/glib-2.0/glib/gqueue.h \
		/usr/include/glib-2.0/glib/grand.h \
		/usr/include/glib-2.0/glib/gregex.h \
		/usr/include/glib-2.0/glib/gscanner.h \
		/usr/include/glib-2.0/glib/gsequence.h \
		/usr/include/glib-2.0/glib/gshell.h \
		/usr/include/glib-2.0/glib/gslice.h \
		/usr/include/glib-2.0/glib/gspawn.h \
		/usr/include/glib-2.0/glib/gstrfuncs.h \
		/usr/include/glib-2.0/glib/gstringchunk.h \
		/usr/include/glib-2.0/glib/gtestutils.h \
		/usr/include/glib-2.0/glib/gthreadpool.h \
		/usr/include/glib-2.0/glib/gtimer.h \
		/usr/include/glib-2.0/glib/gtrashstack.h \
		/usr/include/glib-2.0/glib/gtree.h \
		/usr/include/glib-2.0/glib/gurifuncs.h \
		/usr/include/glib-2.0/glib/gvarianttype.h \
		/usr/include/glib-2.0/glib/gvariant.h \
		/usr/include/glib-2.0/glib/gversion.h \
		/usr/include/glib-2.0/glib/gwin32.h \
		/usr/include/glib-2.0/glib/deprecated/gallocator.h \
		/usr/include/glib-2.0/glib/deprecated/gcache.h \
		/usr/include/glib-2.0/glib/deprecated/gcompletion.h \
		/usr/include/glib-2.0/glib/deprecated/gmain.h \
		/usr/include/glib-2.0/glib/deprecated/grel.h \
		/usr/include/glib-2.0/glib/deprecated/gthread.h \
		/usr/local/include/gstreamer-1.0/gst/gst.h \
		/usr/local/include/gstreamer-1.0/gst/glib-compat.h \
		/usr/local/include/gstreamer-1.0/gst/gstenumtypes.h \
		/usr/include/glib-2.0/glib-object.h \
		/usr/include/glib-2.0/gobject/gbinding.h \
		/usr/include/glib-2.0/gobject/gobject.h \
		/usr/include/glib-2.0/gobject/gtype.h \
		/usr/include/glib-2.0/gobject/gvalue.h \
		/usr/include/glib-2.0/gobject/gparam.h \
		/usr/include/glib-2.0/gobject/gclosure.h \
		/usr/include/glib-2.0/gobject/gsignal.h \
		/usr/include/glib-2.0/gobject/gmarshal.h \
		/usr/include/glib-2.0/gobject/gboxed.h \
		/usr/include/glib-2.0/gobject/glib-types.h \
		/usr/include/glib-2.0/gobject/genums.h \
		/usr/include/glib-2.0/gobject/gparamspecs.h \
		/usr/include/glib-2.0/gobject/gsourceclosure.h \
		/usr/include/glib-2.0/gobject/gtypemodule.h \
		/usr/include/glib-2.0/gobject/gtypeplugin.h \
		/usr/include/glib-2.0/gobject/gvaluearray.h \
		/usr/include/glib-2.0/gobject/gvaluetypes.h \
		/usr/local/include/gstreamer-1.0/gst/gstversion.h \
		/usr/local/include/gstreamer-1.0/gst/gstatomicqueue.h \
		/usr/local/include/gstreamer-1.0/gst/gstbin.h \
		/usr/local/include/gstreamer-1.0/gst/gstelement.h \
		/usr/local/include/gstreamer-1.0/gst/gstconfig.h \
		/usr/local/include/gstreamer-1.0/gst/gstobject.h \
		/usr/local/include/gstreamer-1.0/gst/gstcontrolbinding.h \
		/usr/local/include/gstreamer-1.0/gst/gstcontrolsource.h \
		/usr/local/include/gstreamer-1.0/gst/gstclock.h \
		/usr/local/include/gstreamer-1.0/gst/gstpad.h \
		/usr/local/include/gstreamer-1.0/gst/gstbuffer.h \
		/usr/local/include/gstreamer-1.0/gst/gstminiobject.h \
		/usr/local/include/gstreamer-1.0/gst/gstallocator.h \
		/usr/local/include/gstreamer-1.0/gst/gstmemory.h \
		/usr/local/include/gstreamer-1.0/gst/gstmeta.h \
		/usr/local/include/gstreamer-1.0/gst/gstbufferlist.h \
		/usr/local/include/gstreamer-1.0/gst/gstcaps.h \
		/usr/local/include/gstreamer-1.0/gst/gststructure.h \
		/usr/local/include/gstreamer-1.0/gst/gstdatetime.h \
		/usr/local/include/gstreamer-1.0/gst/gstcapsfeatures.h \
		/usr/local/include/gstreamer-1.0/gst/gstpadtemplate.h \
		/usr/local/include/gstreamer-1.0/gst/gstevent.h \
		/usr/local/include/gstreamer-1.0/gst/gstformat.h \
		/usr/local/include/gstreamer-1.0/gst/gstiterator.h \
		/usr/local/include/gstreamer-1.0/gst/gsttaglist.h \
		/usr/local/include/gstreamer-1.0/gst/gstsample.h \
		/usr/local/include/gstreamer-1.0/gst/gstsegment.h \
		/usr/local/include/gstreamer-1.0/gst/gstmessage.h \
		/usr/local/include/gstreamer-1.0/gst/gstquery.h \
		/usr/local/include/gstreamer-1.0/gst/gsttoc.h \
		/usr/local/include/gstreamer-1.0/gst/gstcontext.h \
		/usr/local/include/gstreamer-1.0/gst/gstdevice.h \
		/usr/local/include/gstreamer-1.0/gst/gsttask.h \
		/usr/local/include/gstreamer-1.0/gst/gsttaskpool.h \
		/usr/local/include/gstreamer-1.0/gst/gstbus.h \
		/usr/local/include/gstreamer-1.0/gst/gstelementfactory.h \
		/usr/local/include/gstreamer-1.0/gst/gstplugin.h \
		/usr/local/include/gstreamer-1.0/gst/gstmacros.h \
		/usr/local/include/gstreamer-1.0/gst/gstpluginfeature.h \
		/usr/local/include/gstreamer-1.0/gst/gsturi.h \
		/usr/local/include/gstreamer-1.0/gst/gstbufferpool.h \
		/usr/local/include/gstreamer-1.0/gst/gstchildproxy.h \
		/usr/local/include/gstreamer-1.0/gst/gstdebugutils.h \
		/usr/local/include/gstreamer-1.0/gst/gstdeviceprovider.h \
		/usr/local/include/gstreamer-1.0/gst/gstdeviceproviderfactory.h \
		/usr/local/include/gstreamer-1.0/gst/gstelementmetadata.h \
		/usr/local/include/gstreamer-1.0/gst/gsterror.h \
		/usr/local/include/gstreamer-1.0/gst/gstghostpad.h \
		/usr/local/include/gstreamer-1.0/gst/gstdevicemonitor.h \
		/usr/local/include/gstreamer-1.0/gst/gstinfo.h \
		/usr/local/include/gstreamer-1.0/gst/gstparamspecs.h \
		/usr/local/include/gstreamer-1.0/gst/gstvalue.h \
		/usr/local/include/gstreamer-1.0/gst/gstpipeline.h \
		/usr/local/include/gstreamer-1.0/gst/gstpoll.h \
		/usr/local/include/gstreamer-1.0/gst/gstpreset.h \
		/usr/local/include/gstreamer-1.0/gst/gstregistry.h \
		/usr/local/include/gstreamer-1.0/gst/gstsystemclock.h \
		/usr/local/include/gstreamer-1.0/gst/gsttagsetter.h \
		/usr/local/include/gstreamer-1.0/gst/gsttocsetter.h \
		/usr/local/include/gstreamer-1.0/gst/gsttypefind.h \
		/usr/local/include/gstreamer-1.0/gst/gsttypefindfactory.h \
		/usr/local/include/gstreamer-1.0/gst/gstutils.h \
		/usr/local/include/gstreamer-1.0/gst/gstparse.h \
		/usr/local/include/gstreamer-1.0/gst/gstcompat.h \
		/usr/local/include/gstreamer-1.0/gst/video/colorbalance.h \
		/usr/local/include/gstreamer-1.0/gst/video/colorbalancechannel.h \
		/usr/local/include/gstreamer-1.0/gst/video/videooverlay.h \
		/usr/include/qt5/QtWidgets/QMessageBox \
		/usr/include/qt5/QtWidgets/qmessagebox.h \
		/usr/include/qt5/QtWidgets/qdialog.h \
		/usr/include/qt5/QtWidgets/QSlider \
		/usr/include/qt5/QtWidgets/qslider.h \
		/usr/include/qt5/QtWidgets/qabstractslider.h \
		/usr/include/qt5/QtWidgets/QLineEdit \
		/usr/include/qt5/QtWidgets/qlineedit.h \
		/usr/include/qt5/QtWidgets/qframe.h \
		/usr/include/qt5/QtGui/qtextcursor.h \
		/usr/include/qt5/QtGui/qtextformat.h \
		/usr/include/qt5/QtGui/qpen.h \
		/usr/include/qt5/QtGui/qtextoption.h \
		/usr/local/include/gstreamer-1.0/gst/audio/streamvolume.h \
		ui_gstvideo.h \
		/usr/include/qt5/QtCore/QVariant \
		/usr/include/qt5/QtWidgets/QAction \
		/usr/include/qt5/QtWidgets/qaction.h \
		/usr/include/qt5/QtGui/qicon.h \
		/usr/include/qt5/QtWidgets/qactiongroup.h \
		/usr/include/qt5/QtWidgets/QApplication \
		/usr/include/qt5/QtWidgets/qapplication.h \
		/usr/include/qt5/QtCore/qcoreapplication.h \
		/usr/include/qt5/QtCore/qeventloop.h \
		/usr/include/qt5/QtWidgets/qdesktopwidget.h \
		/usr/include/qt5/QtGui/qguiapplication.h \
		/usr/include/qt5/QtGui/qinputmethod.h \
		/usr/include/qt5/QtWidgets/QButtonGroup \
		/usr/include/qt5/QtWidgets/qbuttongroup.h \
		/usr/include/qt5/QtWidgets/QComboBox \
		/usr/include/qt5/QtWidgets/qcombobox.h \
		/usr/include/qt5/QtWidgets/qabstractitemdelegate.h \
		/usr/include/qt5/QtWidgets/qstyleoption.h \
		/usr/include/qt5/QtWidgets/qabstractspinbox.h \
		/usr/include/qt5/QtGui/qvalidator.h \
		/usr/include/qt5/QtCore/qregularexpression.h \
		/usr/include/qt5/QtWidgets/qstyle.h \
		/usr/include/qt5/QtWidgets/qtabbar.h \
		/usr/include/qt5/QtWidgets/qtabwidget.h \
		/usr/include/qt5/QtWidgets/qrubberband.h \
		/usr/include/qt5/QtCore/qabstractitemmodel.h \
		/usr/include/qt5/QtWidgets/QHBoxLayout \
		/usr/include/qt5/QtWidgets/qboxlayout.h \
		/usr/include/qt5/QtWidgets/qlayout.h \
		/usr/include/qt5/QtWidgets/qlayoutitem.h \
		/usr/include/qt5/QtWidgets/qgridlayout.h \
		/usr/include/qt5/QtWidgets/QHeaderView \
		/usr/include/qt5/QtWidgets/qheaderview.h \
		/usr/include/qt5/QtWidgets/qabstractitemview.h \
		/usr/include/qt5/QtWidgets/qabstractscrollarea.h \
		/usr/include/qt5/QtCore/qitemselectionmodel.h \
		/usr/include/qt5/QtWidgets/QLabel \
		/usr/include/qt5/QtWidgets/qlabel.h \
		/usr/include/qt5/QtWidgets/QProgressBar \
		/usr/include/qt5/QtWidgets/qprogressbar.h \
		/usr/include/qt5/QtWidgets/QToolButton \
		/usr/include/qt5/QtWidgets/qtoolbutton.h \
		/usr/include/qt5/QtWidgets/qabstractbutton.h \
		/usr/include/qt5/QtWidgets/QVBoxLayout \
		inputbox.h \
		/usr/include/qt5/QtWidgets/QDialog \
		/usr/include/qt5/QtCore/QString
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gstvideo.o gstvideo.cpp

main.o: main.cpp gstvideo.h \
		/usr/include/qt5/QtWidgets/QWidget \
		/usr/include/qt5/QtWidgets/qwidget.h \
		/usr/include/qt5/QtGui/qwindowdefs.h \
		/usr/include/qt5/QtCore/qglobal.h \
		/usr/include/qt5/QtCore/qconfig.h \
		/usr/include/qt5/QtCore/qfeatures.h \
		/usr/include/qt5/QtCore/qsystemdetection.h \
		/usr/include/qt5/QtCore/qprocessordetection.h \
		/usr/include/qt5/QtCore/qcompilerdetection.h \
		/usr/include/qt5/QtCore/qglobalstatic.h \
		/usr/include/qt5/QtCore/qatomic.h \
		/usr/include/qt5/QtCore/qbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/qt5/QtCore/qgenericatomic.h \
		/usr/include/qt5/QtCore/qatomic_msvc.h \
		/usr/include/qt5/QtCore/qatomic_integrity.h \
		/usr/include/qt5/QtCore/qoldbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_vxworks.h \
		/usr/include/qt5/QtCore/qatomic_power.h \
		/usr/include/qt5/QtCore/qatomic_alpha.h \
		/usr/include/qt5/QtCore/qatomic_armv7.h \
		/usr/include/qt5/QtCore/qatomic_armv6.h \
		/usr/include/qt5/QtCore/qatomic_armv5.h \
		/usr/include/qt5/QtCore/qatomic_bfin.h \
		/usr/include/qt5/QtCore/qatomic_ia64.h \
		/usr/include/qt5/QtCore/qatomic_mips.h \
		/usr/include/qt5/QtCore/qatomic_s390.h \
		/usr/include/qt5/QtCore/qatomic_sh4a.h \
		/usr/include/qt5/QtCore/qatomic_sparc.h \
		/usr/include/qt5/QtCore/qatomic_gcc.h \
		/usr/include/qt5/QtCore/qatomic_x86.h \
		/usr/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/qt5/QtCore/qatomic_unix.h \
		/usr/include/qt5/QtCore/qmutex.h \
		/usr/include/qt5/QtCore/qlogging.h \
		/usr/include/qt5/QtCore/qflags.h \
		/usr/include/qt5/QtCore/qtypeinfo.h \
		/usr/include/qt5/QtCore/qtypetraits.h \
		/usr/include/qt5/QtCore/qsysinfo.h \
		/usr/include/qt5/QtCore/qobjectdefs.h \
		/usr/include/qt5/QtCore/qnamespace.h \
		/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/qt5/QtCore/qobject.h \
		/usr/include/qt5/QtCore/qstring.h \
		/usr/include/qt5/QtCore/qchar.h \
		/usr/include/qt5/QtCore/qbytearray.h \
		/usr/include/qt5/QtCore/qrefcount.h \
		/usr/include/qt5/QtCore/qarraydata.h \
		/usr/include/qt5/QtCore/qstringbuilder.h \
		/usr/include/qt5/QtCore/qlist.h \
		/usr/include/qt5/QtCore/qalgorithms.h \
		/usr/include/qt5/QtCore/qiterator.h \
		/usr/include/qt5/QtCore/qcoreevent.h \
		/usr/include/qt5/QtCore/qscopedpointer.h \
		/usr/include/qt5/QtCore/qmetatype.h \
		/usr/include/qt5/QtCore/qvarlengtharray.h \
		/usr/include/qt5/QtCore/qcontainerfwd.h \
		/usr/include/qt5/QtCore/qisenum.h \
		/usr/include/qt5/QtCore/qobject_impl.h \
		/usr/include/qt5/QtCore/qmargins.h \
		/usr/include/qt5/QtCore/qrect.h \
		/usr/include/qt5/QtCore/qsize.h \
		/usr/include/qt5/QtCore/qpoint.h \
		/usr/include/qt5/QtGui/qpaintdevice.h \
		/usr/include/qt5/QtGui/qpalette.h \
		/usr/include/qt5/QtGui/qcolor.h \
		/usr/include/qt5/QtGui/qrgb.h \
		/usr/include/qt5/QtCore/qstringlist.h \
		/usr/include/qt5/QtCore/qdatastream.h \
		/usr/include/qt5/QtCore/qiodevice.h \
		/usr/include/qt5/QtCore/qpair.h \
		/usr/include/qt5/QtCore/qregexp.h \
		/usr/include/qt5/QtCore/qstringmatcher.h \
		/usr/include/qt5/QtGui/qbrush.h \
		/usr/include/qt5/QtCore/qvector.h \
		/usr/include/qt5/QtGui/qmatrix.h \
		/usr/include/qt5/QtGui/qpolygon.h \
		/usr/include/qt5/QtGui/qregion.h \
		/usr/include/qt5/QtCore/qline.h \
		/usr/include/qt5/QtGui/qtransform.h \
		/usr/include/qt5/QtGui/qpainterpath.h \
		/usr/include/qt5/QtGui/qimage.h \
		/usr/include/qt5/QtGui/qpixmap.h \
		/usr/include/qt5/QtCore/qsharedpointer.h \
		/usr/include/qt5/QtCore/qshareddata.h \
		/usr/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/qt5/QtCore/qhash.h \
		/usr/include/qt5/QtGui/qfont.h \
		/usr/include/qt5/QtGui/qfontmetrics.h \
		/usr/include/qt5/QtGui/qfontinfo.h \
		/usr/include/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/qt5/QtGui/qcursor.h \
		/usr/include/qt5/QtGui/qkeysequence.h \
		/usr/include/qt5/QtGui/qevent.h \
		/usr/include/qt5/QtCore/qvariant.h \
		/usr/include/qt5/QtCore/qmap.h \
		/usr/include/qt5/QtCore/qdebug.h \
		/usr/include/qt5/QtCore/qtextstream.h \
		/usr/include/qt5/QtCore/qlocale.h \
		/usr/include/qt5/QtCore/qset.h \
		/usr/include/qt5/QtCore/qcontiguouscache.h \
		/usr/include/qt5/QtCore/qurl.h \
		/usr/include/qt5/QtCore/qurlquery.h \
		/usr/include/qt5/QtCore/qfile.h \
		/usr/include/qt5/QtCore/qfiledevice.h \
		/usr/include/qt5/QtGui/qvector2d.h \
		/usr/include/qt5/QtGui/qtouchdevice.h \
		/usr/include/glib-2.0/glib.h \
		/usr/include/glib-2.0/glib/galloca.h \
		/usr/include/glib-2.0/glib/gtypes.h \
		/usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h \
		/usr/include/glib-2.0/glib/gmacros.h \
		/usr/include/glib-2.0/glib/gversionmacros.h \
		/usr/include/glib-2.0/glib/garray.h \
		/usr/include/glib-2.0/glib/gasyncqueue.h \
		/usr/include/glib-2.0/glib/gthread.h \
		/usr/include/glib-2.0/glib/gatomic.h \
		/usr/include/glib-2.0/glib/gerror.h \
		/usr/include/glib-2.0/glib/gquark.h \
		/usr/include/glib-2.0/glib/gbacktrace.h \
		/usr/include/glib-2.0/glib/gbase64.h \
		/usr/include/glib-2.0/glib/gbitlock.h \
		/usr/include/glib-2.0/glib/gbookmarkfile.h \
		/usr/include/glib-2.0/glib/gbytes.h \
		/usr/include/glib-2.0/glib/gcharset.h \
		/usr/include/glib-2.0/glib/gchecksum.h \
		/usr/include/glib-2.0/glib/gconvert.h \
		/usr/include/glib-2.0/glib/gdataset.h \
		/usr/include/glib-2.0/glib/gdate.h \
		/usr/include/glib-2.0/glib/gdatetime.h \
		/usr/include/glib-2.0/glib/gtimezone.h \
		/usr/include/glib-2.0/glib/gdir.h \
		/usr/include/glib-2.0/glib/genviron.h \
		/usr/include/glib-2.0/glib/gfileutils.h \
		/usr/include/glib-2.0/glib/ggettext.h \
		/usr/include/glib-2.0/glib/ghash.h \
		/usr/include/glib-2.0/glib/glist.h \
		/usr/include/glib-2.0/glib/gmem.h \
		/usr/include/glib-2.0/glib/gnode.h \
		/usr/include/glib-2.0/glib/ghmac.h \
		/usr/include/glib-2.0/glib/ghook.h \
		/usr/include/glib-2.0/glib/ghostutils.h \
		/usr/include/glib-2.0/glib/giochannel.h \
		/usr/include/glib-2.0/glib/gmain.h \
		/usr/include/glib-2.0/glib/gpoll.h \
		/usr/include/glib-2.0/glib/gslist.h \
		/usr/include/glib-2.0/glib/gstring.h \
		/usr/include/glib-2.0/glib/gunicode.h \
		/usr/include/glib-2.0/glib/gutils.h \
		/usr/include/glib-2.0/glib/gkeyfile.h \
		/usr/include/glib-2.0/glib/gmappedfile.h \
		/usr/include/glib-2.0/glib/gmarkup.h \
		/usr/include/glib-2.0/glib/gmessages.h \
		/usr/include/glib-2.0/glib/goption.h \
		/usr/include/glib-2.0/glib/gpattern.h \
		/usr/include/glib-2.0/glib/gprimes.h \
		/usr/include/glib-2.0/glib/gqsort.h \
		/usr/include/glib-2.0/glib/gqueue.h \
		/usr/include/glib-2.0/glib/grand.h \
		/usr/include/glib-2.0/glib/gregex.h \
		/usr/include/glib-2.0/glib/gscanner.h \
		/usr/include/glib-2.0/glib/gsequence.h \
		/usr/include/glib-2.0/glib/gshell.h \
		/usr/include/glib-2.0/glib/gslice.h \
		/usr/include/glib-2.0/glib/gspawn.h \
		/usr/include/glib-2.0/glib/gstrfuncs.h \
		/usr/include/glib-2.0/glib/gstringchunk.h \
		/usr/include/glib-2.0/glib/gtestutils.h \
		/usr/include/glib-2.0/glib/gthreadpool.h \
		/usr/include/glib-2.0/glib/gtimer.h \
		/usr/include/glib-2.0/glib/gtrashstack.h \
		/usr/include/glib-2.0/glib/gtree.h \
		/usr/include/glib-2.0/glib/gurifuncs.h \
		/usr/include/glib-2.0/glib/gvarianttype.h \
		/usr/include/glib-2.0/glib/gvariant.h \
		/usr/include/glib-2.0/glib/gversion.h \
		/usr/include/glib-2.0/glib/gwin32.h \
		/usr/include/glib-2.0/glib/deprecated/gallocator.h \
		/usr/include/glib-2.0/glib/deprecated/gcache.h \
		/usr/include/glib-2.0/glib/deprecated/gcompletion.h \
		/usr/include/glib-2.0/glib/deprecated/gmain.h \
		/usr/include/glib-2.0/glib/deprecated/grel.h \
		/usr/include/glib-2.0/glib/deprecated/gthread.h \
		/usr/local/include/gstreamer-1.0/gst/gst.h \
		/usr/local/include/gstreamer-1.0/gst/glib-compat.h \
		/usr/local/include/gstreamer-1.0/gst/gstenumtypes.h \
		/usr/include/glib-2.0/glib-object.h \
		/usr/include/glib-2.0/gobject/gbinding.h \
		/usr/include/glib-2.0/gobject/gobject.h \
		/usr/include/glib-2.0/gobject/gtype.h \
		/usr/include/glib-2.0/gobject/gvalue.h \
		/usr/include/glib-2.0/gobject/gparam.h \
		/usr/include/glib-2.0/gobject/gclosure.h \
		/usr/include/glib-2.0/gobject/gsignal.h \
		/usr/include/glib-2.0/gobject/gmarshal.h \
		/usr/include/glib-2.0/gobject/gboxed.h \
		/usr/include/glib-2.0/gobject/glib-types.h \
		/usr/include/glib-2.0/gobject/genums.h \
		/usr/include/glib-2.0/gobject/gparamspecs.h \
		/usr/include/glib-2.0/gobject/gsourceclosure.h \
		/usr/include/glib-2.0/gobject/gtypemodule.h \
		/usr/include/glib-2.0/gobject/gtypeplugin.h \
		/usr/include/glib-2.0/gobject/gvaluearray.h \
		/usr/include/glib-2.0/gobject/gvaluetypes.h \
		/usr/local/include/gstreamer-1.0/gst/gstversion.h \
		/usr/local/include/gstreamer-1.0/gst/gstatomicqueue.h \
		/usr/local/include/gstreamer-1.0/gst/gstbin.h \
		/usr/local/include/gstreamer-1.0/gst/gstelement.h \
		/usr/local/include/gstreamer-1.0/gst/gstconfig.h \
		/usr/local/include/gstreamer-1.0/gst/gstobject.h \
		/usr/local/include/gstreamer-1.0/gst/gstcontrolbinding.h \
		/usr/local/include/gstreamer-1.0/gst/gstcontrolsource.h \
		/usr/local/include/gstreamer-1.0/gst/gstclock.h \
		/usr/local/include/gstreamer-1.0/gst/gstpad.h \
		/usr/local/include/gstreamer-1.0/gst/gstbuffer.h \
		/usr/local/include/gstreamer-1.0/gst/gstminiobject.h \
		/usr/local/include/gstreamer-1.0/gst/gstallocator.h \
		/usr/local/include/gstreamer-1.0/gst/gstmemory.h \
		/usr/local/include/gstreamer-1.0/gst/gstmeta.h \
		/usr/local/include/gstreamer-1.0/gst/gstbufferlist.h \
		/usr/local/include/gstreamer-1.0/gst/gstcaps.h \
		/usr/local/include/gstreamer-1.0/gst/gststructure.h \
		/usr/local/include/gstreamer-1.0/gst/gstdatetime.h \
		/usr/local/include/gstreamer-1.0/gst/gstcapsfeatures.h \
		/usr/local/include/gstreamer-1.0/gst/gstpadtemplate.h \
		/usr/local/include/gstreamer-1.0/gst/gstevent.h \
		/usr/local/include/gstreamer-1.0/gst/gstformat.h \
		/usr/local/include/gstreamer-1.0/gst/gstiterator.h \
		/usr/local/include/gstreamer-1.0/gst/gsttaglist.h \
		/usr/local/include/gstreamer-1.0/gst/gstsample.h \
		/usr/local/include/gstreamer-1.0/gst/gstsegment.h \
		/usr/local/include/gstreamer-1.0/gst/gstmessage.h \
		/usr/local/include/gstreamer-1.0/gst/gstquery.h \
		/usr/local/include/gstreamer-1.0/gst/gsttoc.h \
		/usr/local/include/gstreamer-1.0/gst/gstcontext.h \
		/usr/local/include/gstreamer-1.0/gst/gstdevice.h \
		/usr/local/include/gstreamer-1.0/gst/gsttask.h \
		/usr/local/include/gstreamer-1.0/gst/gsttaskpool.h \
		/usr/local/include/gstreamer-1.0/gst/gstbus.h \
		/usr/local/include/gstreamer-1.0/gst/gstelementfactory.h \
		/usr/local/include/gstreamer-1.0/gst/gstplugin.h \
		/usr/local/include/gstreamer-1.0/gst/gstmacros.h \
		/usr/local/include/gstreamer-1.0/gst/gstpluginfeature.h \
		/usr/local/include/gstreamer-1.0/gst/gsturi.h \
		/usr/local/include/gstreamer-1.0/gst/gstbufferpool.h \
		/usr/local/include/gstreamer-1.0/gst/gstchildproxy.h \
		/usr/local/include/gstreamer-1.0/gst/gstdebugutils.h \
		/usr/local/include/gstreamer-1.0/gst/gstdeviceprovider.h \
		/usr/local/include/gstreamer-1.0/gst/gstdeviceproviderfactory.h \
		/usr/local/include/gstreamer-1.0/gst/gstelementmetadata.h \
		/usr/local/include/gstreamer-1.0/gst/gsterror.h \
		/usr/local/include/gstreamer-1.0/gst/gstghostpad.h \
		/usr/local/include/gstreamer-1.0/gst/gstdevicemonitor.h \
		/usr/local/include/gstreamer-1.0/gst/gstinfo.h \
		/usr/local/include/gstreamer-1.0/gst/gstparamspecs.h \
		/usr/local/include/gstreamer-1.0/gst/gstvalue.h \
		/usr/local/include/gstreamer-1.0/gst/gstpipeline.h \
		/usr/local/include/gstreamer-1.0/gst/gstpoll.h \
		/usr/local/include/gstreamer-1.0/gst/gstpreset.h \
		/usr/local/include/gstreamer-1.0/gst/gstregistry.h \
		/usr/local/include/gstreamer-1.0/gst/gstsystemclock.h \
		/usr/local/include/gstreamer-1.0/gst/gsttagsetter.h \
		/usr/local/include/gstreamer-1.0/gst/gsttocsetter.h \
		/usr/local/include/gstreamer-1.0/gst/gsttypefind.h \
		/usr/local/include/gstreamer-1.0/gst/gsttypefindfactory.h \
		/usr/local/include/gstreamer-1.0/gst/gstutils.h \
		/usr/local/include/gstreamer-1.0/gst/gstparse.h \
		/usr/local/include/gstreamer-1.0/gst/gstcompat.h \
		/usr/local/include/gstreamer-1.0/gst/video/colorbalance.h \
		/usr/local/include/gstreamer-1.0/gst/video/colorbalancechannel.h \
		/usr/local/include/gstreamer-1.0/gst/video/videooverlay.h \
		/usr/include/qt5/QtWidgets/QMessageBox \
		/usr/include/qt5/QtWidgets/qmessagebox.h \
		/usr/include/qt5/QtWidgets/qdialog.h \
		/usr/include/qt5/QtWidgets/QSlider \
		/usr/include/qt5/QtWidgets/qslider.h \
		/usr/include/qt5/QtWidgets/qabstractslider.h \
		/usr/include/qt5/QtWidgets/QLineEdit \
		/usr/include/qt5/QtWidgets/qlineedit.h \
		/usr/include/qt5/QtWidgets/qframe.h \
		/usr/include/qt5/QtGui/qtextcursor.h \
		/usr/include/qt5/QtGui/qtextformat.h \
		/usr/include/qt5/QtGui/qpen.h \
		/usr/include/qt5/QtGui/qtextoption.h \
		/usr/local/include/gstreamer-1.0/gst/audio/streamvolume.h \
		ui_gstvideo.h \
		/usr/include/qt5/QtCore/QVariant \
		/usr/include/qt5/QtWidgets/QAction \
		/usr/include/qt5/QtWidgets/qaction.h \
		/usr/include/qt5/QtGui/qicon.h \
		/usr/include/qt5/QtWidgets/qactiongroup.h \
		/usr/include/qt5/QtWidgets/QApplication \
		/usr/include/qt5/QtWidgets/qapplication.h \
		/usr/include/qt5/QtCore/qcoreapplication.h \
		/usr/include/qt5/QtCore/qeventloop.h \
		/usr/include/qt5/QtWidgets/qdesktopwidget.h \
		/usr/include/qt5/QtGui/qguiapplication.h \
		/usr/include/qt5/QtGui/qinputmethod.h \
		/usr/include/qt5/QtWidgets/QButtonGroup \
		/usr/include/qt5/QtWidgets/qbuttongroup.h \
		/usr/include/qt5/QtWidgets/QComboBox \
		/usr/include/qt5/QtWidgets/qcombobox.h \
		/usr/include/qt5/QtWidgets/qabstractitemdelegate.h \
		/usr/include/qt5/QtWidgets/qstyleoption.h \
		/usr/include/qt5/QtWidgets/qabstractspinbox.h \
		/usr/include/qt5/QtGui/qvalidator.h \
		/usr/include/qt5/QtCore/qregularexpression.h \
		/usr/include/qt5/QtWidgets/qstyle.h \
		/usr/include/qt5/QtWidgets/qtabbar.h \
		/usr/include/qt5/QtWidgets/qtabwidget.h \
		/usr/include/qt5/QtWidgets/qrubberband.h \
		/usr/include/qt5/QtCore/qabstractitemmodel.h \
		/usr/include/qt5/QtWidgets/QHBoxLayout \
		/usr/include/qt5/QtWidgets/qboxlayout.h \
		/usr/include/qt5/QtWidgets/qlayout.h \
		/usr/include/qt5/QtWidgets/qlayoutitem.h \
		/usr/include/qt5/QtWidgets/qgridlayout.h \
		/usr/include/qt5/QtWidgets/QHeaderView \
		/usr/include/qt5/QtWidgets/qheaderview.h \
		/usr/include/qt5/QtWidgets/qabstractitemview.h \
		/usr/include/qt5/QtWidgets/qabstractscrollarea.h \
		/usr/include/qt5/QtCore/qitemselectionmodel.h \
		/usr/include/qt5/QtWidgets/QLabel \
		/usr/include/qt5/QtWidgets/qlabel.h \
		/usr/include/qt5/QtWidgets/QProgressBar \
		/usr/include/qt5/QtWidgets/qprogressbar.h \
		/usr/include/qt5/QtWidgets/QToolButton \
		/usr/include/qt5/QtWidgets/qtoolbutton.h \
		/usr/include/qt5/QtWidgets/qabstractbutton.h \
		/usr/include/qt5/QtWidgets/QVBoxLayout \
		inputbox.h \
		/usr/include/qt5/QtWidgets/QDialog \
		/usr/include/qt5/QtCore/QString
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

inputbox.o: inputbox.cpp inputbox.h \
		/usr/include/qt5/QtWidgets/QDialog \
		/usr/include/qt5/QtWidgets/qdialog.h \
		/usr/include/qt5/QtWidgets/qwidget.h \
		/usr/include/qt5/QtGui/qwindowdefs.h \
		/usr/include/qt5/QtCore/qglobal.h \
		/usr/include/qt5/QtCore/qconfig.h \
		/usr/include/qt5/QtCore/qfeatures.h \
		/usr/include/qt5/QtCore/qsystemdetection.h \
		/usr/include/qt5/QtCore/qprocessordetection.h \
		/usr/include/qt5/QtCore/qcompilerdetection.h \
		/usr/include/qt5/QtCore/qglobalstatic.h \
		/usr/include/qt5/QtCore/qatomic.h \
		/usr/include/qt5/QtCore/qbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		/usr/include/qt5/QtCore/qgenericatomic.h \
		/usr/include/qt5/QtCore/qatomic_msvc.h \
		/usr/include/qt5/QtCore/qatomic_integrity.h \
		/usr/include/qt5/QtCore/qoldbasicatomic.h \
		/usr/include/qt5/QtCore/qatomic_vxworks.h \
		/usr/include/qt5/QtCore/qatomic_power.h \
		/usr/include/qt5/QtCore/qatomic_alpha.h \
		/usr/include/qt5/QtCore/qatomic_armv7.h \
		/usr/include/qt5/QtCore/qatomic_armv6.h \
		/usr/include/qt5/QtCore/qatomic_armv5.h \
		/usr/include/qt5/QtCore/qatomic_bfin.h \
		/usr/include/qt5/QtCore/qatomic_ia64.h \
		/usr/include/qt5/QtCore/qatomic_mips.h \
		/usr/include/qt5/QtCore/qatomic_s390.h \
		/usr/include/qt5/QtCore/qatomic_sh4a.h \
		/usr/include/qt5/QtCore/qatomic_sparc.h \
		/usr/include/qt5/QtCore/qatomic_gcc.h \
		/usr/include/qt5/QtCore/qatomic_x86.h \
		/usr/include/qt5/QtCore/qatomic_cxx11.h \
		/usr/include/qt5/QtCore/qatomic_unix.h \
		/usr/include/qt5/QtCore/qmutex.h \
		/usr/include/qt5/QtCore/qlogging.h \
		/usr/include/qt5/QtCore/qflags.h \
		/usr/include/qt5/QtCore/qtypeinfo.h \
		/usr/include/qt5/QtCore/qtypetraits.h \
		/usr/include/qt5/QtCore/qsysinfo.h \
		/usr/include/qt5/QtCore/qobjectdefs.h \
		/usr/include/qt5/QtCore/qnamespace.h \
		/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		/usr/include/qt5/QtGui/qwindowdefs_win.h \
		/usr/include/qt5/QtCore/qobject.h \
		/usr/include/qt5/QtCore/qstring.h \
		/usr/include/qt5/QtCore/qchar.h \
		/usr/include/qt5/QtCore/qbytearray.h \
		/usr/include/qt5/QtCore/qrefcount.h \
		/usr/include/qt5/QtCore/qarraydata.h \
		/usr/include/qt5/QtCore/qstringbuilder.h \
		/usr/include/qt5/QtCore/qlist.h \
		/usr/include/qt5/QtCore/qalgorithms.h \
		/usr/include/qt5/QtCore/qiterator.h \
		/usr/include/qt5/QtCore/qcoreevent.h \
		/usr/include/qt5/QtCore/qscopedpointer.h \
		/usr/include/qt5/QtCore/qmetatype.h \
		/usr/include/qt5/QtCore/qvarlengtharray.h \
		/usr/include/qt5/QtCore/qcontainerfwd.h \
		/usr/include/qt5/QtCore/qisenum.h \
		/usr/include/qt5/QtCore/qobject_impl.h \
		/usr/include/qt5/QtCore/qmargins.h \
		/usr/include/qt5/QtCore/qrect.h \
		/usr/include/qt5/QtCore/qsize.h \
		/usr/include/qt5/QtCore/qpoint.h \
		/usr/include/qt5/QtGui/qpaintdevice.h \
		/usr/include/qt5/QtGui/qpalette.h \
		/usr/include/qt5/QtGui/qcolor.h \
		/usr/include/qt5/QtGui/qrgb.h \
		/usr/include/qt5/QtCore/qstringlist.h \
		/usr/include/qt5/QtCore/qdatastream.h \
		/usr/include/qt5/QtCore/qiodevice.h \
		/usr/include/qt5/QtCore/qpair.h \
		/usr/include/qt5/QtCore/qregexp.h \
		/usr/include/qt5/QtCore/qstringmatcher.h \
		/usr/include/qt5/QtGui/qbrush.h \
		/usr/include/qt5/QtCore/qvector.h \
		/usr/include/qt5/QtGui/qmatrix.h \
		/usr/include/qt5/QtGui/qpolygon.h \
		/usr/include/qt5/QtGui/qregion.h \
		/usr/include/qt5/QtCore/qline.h \
		/usr/include/qt5/QtGui/qtransform.h \
		/usr/include/qt5/QtGui/qpainterpath.h \
		/usr/include/qt5/QtGui/qimage.h \
		/usr/include/qt5/QtGui/qpixmap.h \
		/usr/include/qt5/QtCore/qsharedpointer.h \
		/usr/include/qt5/QtCore/qshareddata.h \
		/usr/include/qt5/QtCore/qsharedpointer_impl.h \
		/usr/include/qt5/QtCore/qhash.h \
		/usr/include/qt5/QtGui/qfont.h \
		/usr/include/qt5/QtGui/qfontmetrics.h \
		/usr/include/qt5/QtGui/qfontinfo.h \
		/usr/include/qt5/QtWidgets/qsizepolicy.h \
		/usr/include/qt5/QtGui/qcursor.h \
		/usr/include/qt5/QtGui/qkeysequence.h \
		/usr/include/qt5/QtGui/qevent.h \
		/usr/include/qt5/QtCore/qvariant.h \
		/usr/include/qt5/QtCore/qmap.h \
		/usr/include/qt5/QtCore/qdebug.h \
		/usr/include/qt5/QtCore/qtextstream.h \
		/usr/include/qt5/QtCore/qlocale.h \
		/usr/include/qt5/QtCore/qset.h \
		/usr/include/qt5/QtCore/qcontiguouscache.h \
		/usr/include/qt5/QtCore/qurl.h \
		/usr/include/qt5/QtCore/qurlquery.h \
		/usr/include/qt5/QtCore/qfile.h \
		/usr/include/qt5/QtCore/qfiledevice.h \
		/usr/include/qt5/QtGui/qvector2d.h \
		/usr/include/qt5/QtGui/qtouchdevice.h \
		/usr/include/qt5/QtCore/QString \
		ui_inputbox.h \
		/usr/include/qt5/QtCore/QVariant \
		/usr/include/qt5/QtWidgets/QAction \
		/usr/include/qt5/QtWidgets/qaction.h \
		/usr/include/qt5/QtGui/qicon.h \
		/usr/include/qt5/QtWidgets/qactiongroup.h \
		/usr/include/qt5/QtWidgets/QApplication \
		/usr/include/qt5/QtWidgets/qapplication.h \
		/usr/include/qt5/QtCore/qcoreapplication.h \
		/usr/include/qt5/QtCore/qeventloop.h \
		/usr/include/qt5/QtWidgets/qdesktopwidget.h \
		/usr/include/qt5/QtGui/qguiapplication.h \
		/usr/include/qt5/QtGui/qinputmethod.h \
		/usr/include/qt5/QtWidgets/QButtonGroup \
		/usr/include/qt5/QtWidgets/qbuttongroup.h \
		/usr/include/qt5/QtWidgets/QCheckBox \
		/usr/include/qt5/QtWidgets/qcheckbox.h \
		/usr/include/qt5/QtWidgets/qabstractbutton.h \
		/usr/include/qt5/QtWidgets/QComboBox \
		/usr/include/qt5/QtWidgets/qcombobox.h \
		/usr/include/qt5/QtWidgets/qabstractitemdelegate.h \
		/usr/include/qt5/QtWidgets/qstyleoption.h \
		/usr/include/qt5/QtWidgets/qabstractspinbox.h \
		/usr/include/qt5/QtGui/qvalidator.h \
		/usr/include/qt5/QtCore/qregularexpression.h \
		/usr/include/qt5/QtWidgets/qslider.h \
		/usr/include/qt5/QtWidgets/qabstractslider.h \
		/usr/include/qt5/QtWidgets/qstyle.h \
		/usr/include/qt5/QtWidgets/qtabbar.h \
		/usr/include/qt5/QtWidgets/qtabwidget.h \
		/usr/include/qt5/QtWidgets/qrubberband.h \
		/usr/include/qt5/QtWidgets/qframe.h \
		/usr/include/qt5/QtCore/qabstractitemmodel.h \
		/usr/include/qt5/QtWidgets/QDialogButtonBox \
		/usr/include/qt5/QtWidgets/qdialogbuttonbox.h \
		/usr/include/qt5/QtWidgets/QHBoxLayout \
		/usr/include/qt5/QtWidgets/qboxlayout.h \
		/usr/include/qt5/QtWidgets/qlayout.h \
		/usr/include/qt5/QtWidgets/qlayoutitem.h \
		/usr/include/qt5/QtWidgets/qgridlayout.h \
		/usr/include/qt5/QtWidgets/QHeaderView \
		/usr/include/qt5/QtWidgets/qheaderview.h \
		/usr/include/qt5/QtWidgets/qabstractitemview.h \
		/usr/include/qt5/QtWidgets/qabstractscrollarea.h \
		/usr/include/qt5/QtCore/qitemselectionmodel.h \
		/usr/include/qt5/QtWidgets/QLabel \
		/usr/include/qt5/QtWidgets/qlabel.h \
		/usr/include/qt5/QtWidgets/QLineEdit \
		/usr/include/qt5/QtWidgets/qlineedit.h \
		/usr/include/qt5/QtGui/qtextcursor.h \
		/usr/include/qt5/QtGui/qtextformat.h \
		/usr/include/qt5/QtGui/qpen.h \
		/usr/include/qt5/QtGui/qtextoption.h \
		/usr/include/qt5/QtWidgets/QVBoxLayout \
		/usr/include/qt5/QtWidgets/QWidget
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o inputbox.o inputbox.cpp

moc_gstvideo.o: moc_gstvideo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gstvideo.o moc_gstvideo.cpp

moc_inputbox.o: moc_inputbox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_inputbox.o moc_inputbox.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

